### ISSUE TITLE
Include Inpsyde composer plugin for downloading translation files

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-multilingual#19]
Inpsyde have developed a composer plugin that reads config from the root project composer file and downloads core, theme and plugin translation files available on wordpress.org.

https://github.com/inpsyde/wp-translation-downloader

It would be simple to add as a dependency here and to document the configuration needed.

There are potential caveats however eg. git ignoring the downloaded files vs those that need to be added to version control.

**Comment by johnbillion** [comment]
I wonder how it handles versioning. We don't want to be stuck with the translations that were available at the point in time where a plugin was released. I'm sure Inpsyde have thought of this, just needs checking.

**Comment by roborourke** [comment]
Yeah I did wonder about that but I'm sure they would. This issue definitely needs a bit of research first, in particular around providing our own custom code translations but seems like a decent approach that we could extend for fetching everything at build time given that composer is required anyway.

**Comment by rmccue** [comment]
Closing out as a won't do for now, we can add to Productboard if requested.
