### ISSUE TITLE
Docs for including MultilingualPress

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-multilingual#2]
We can describe the advanced features of MultilingualPress and suggest it as a recommended solution if a project needs more advanced multi language support.

**Comment by rmccue** [comment]
Bumping this off the 3.0 milestone for now. We've seen some issues with MultilingualPress as we've used it more, so going to hold off for now.

**Comment by jennybeaumont** [comment]
Won't do

**Comment by bueltge** [comment]
If you need our help @jennybeaumont feel free to ask, write to me.

**Comment by roborourke** [comment]
@bueltge hey - for context this was closed because there’s no special config changes to make in order to run MLP on Altis so we’re adding it to a list of pre approved plugins instead of documenting it here.

**Comment by bueltge** [comment]
Thanks for your clarification @roborourke  My comment should only point put, that we would help if we can. No tasks, if not necessary.

**Comment by roborourke** [comment]
Yeah of course, sorry - definitely appreciate you reaching out here! Would love to chat about maybe having Inpsyde as a tech partner at some point if it's of benefit to you as well.
