### ISSUE TITLE
Include loco-translate as a way for UI translation management

### ISSUE THREAD

**Issue by shadyvb** [humanmade/altis-multilingual#24]
Current recommended way of translating UI components is to use CLI commands to generate POT files, hand them over to translators, and then programmatically include the updated translation files via revision control.

On another project, we've used loco-translate to manage UI translations, where the plugin manages updating POT files via the front-end and/or CLI commands, and makes updated list of strings available for translators to translate them right within the admin UI. Such update translation files are then saved to the uploads directory, which is synced to all web servers as it is hosted on S3.

Only caveat ATM is that the string extraction process ( updating POT files ) can take a bit more than 60 seconds and thus would timeout on production environments, but this is something that can probably be fixed / worked around, with the CLI invocation of the command available as fallback.

How is this useful ?
- It enables translators to have autonomy, without depending on releases and development workflows to do their job.
- It eliminates the need for any external tooling or prior knowledge of how translations work.

Thoughts ?

**Comment by rmccue** [comment]
I think ideally, we would prefer to have this in the Altis Dashboard instead. This then allows us to pull the strings out at build time, rather than live.

**Comment by roborourke** [comment]
It's gonna be a long time before we figure out a way to integrate or worse build a UI for this in the Altis dashboard so this could get us there way quicker. Furthermore the same tool could be used by us to translate all the Altis code from the Dashboard backend - that could then be used as an API / source for the https://github.com/inpsyde/wp-translation-downloader composer plugin and we could integrate that too.

If it's not something we bundle the plugin itself could be the thing that sits behind any translation UI we put on the dashboard.

Could use a research spike anyway. I have a few questions @shadyvb:

- Does Loco operate behave any differently on multisite? Is there a network admin only mode?
- Does it have any built in user roles / capabilltiies for translators?
- Does it provide any API endpoints or access to its data in ways other than the admin?
- Is there a lot of branding etc? Can we make look like a more seamless part of Altis easily?
- Is it a free OS or premium plugin, and can it be installed via composer? Is it on packagist.org or only wpackagist?

**Comment by rmccue** [comment]
Let's track in Productboard instead.
